Vet clinic database: add "join table" for visits
Innocent259/Vet-clinic pull request #4
Opened 2023-08-18 18:26 UTC by Innocent259

In this project milestone I:

1. Created a "vets" table for veterinary professional information.
2. Established many-to-many relationships between vets and species using "specializations."
3. Managed animal-vet interactions with the "visits" table, recording visit dates.
4. Added vet data, specialized species, and visit records.
5. Answered questions using JOIN queries for insights.

![Screenshot from 2023-08-18 19-57-21](https://github.com/Innocent259/Vet-clinic/assets/108480851/53b62aaa-fcb3-45d0-b566-8de07aebeef2)

![Screenshot from 2023-08-18 19-56-11](https://github.com/Innocent259/Vet-clinic/assets/108480851/df11e3e3-e15f-4f59-9e8a-8e35cd8e55f4)

![Screenshot from 2023-08-18 19-54-13](https://github.com/Innocent259/Vet-clinic/assets/108480851/9e13fe6d-ad2d-4bd5-8450-b35ccf11639b)

![Screenshot from 2023-08-18 19-53-11](https://github.com/Innocent259/Vet-clinic/assets/108480851/e77c3619-fe31-4fbe-af3e-125a87f31da1)

![Screenshot from 2023-08-18 19-52-09](https://github.com/Innocent259/Vet-clinic/assets/108480851/0d6d01c0-0542-43f1-a806-d14f3774f35e)

![Screenshot from 2023-08-18 19-50-41](https://github.com/Innocent259/Vet-clinic/assets/108480851/e9706771-37e4-47bc-af38-c501da3ed1f0)

![Screenshot from 2023-08-18 20-00-46](https://github.com/Innocent259/Vet-clinic/assets/108480851/202804e9-6edb-4a11-9572-73eecc51ed21)

![Screenshot from 2023-08-18 19-59-43](https://github.com/Innocent259/Vet-clinic/assets/108480851/5a3b4d0a-450e-4d75-8952-89e6654ac385)

![Screenshot from 2023-08-18 19-58-38](https://github.com/Innocent259/Vet-clinic/assets/108480851/fa692998-045c-42c5-b66d-2e386cd990e9)

2023-08-18 19:17 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![Ukhv](https://user-images.githubusercontent.com/93039359/247195854-e274f284-2e3a-423b-8939-7e4efb638ee0.gif)

## Hey @Innocent259 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements
✔️ Well Structured Database 👍 🔥
✔️ Great use of JOINS ⛓️

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 19:17 UTC, HAMMAS-SALEEM commented on queries.sql
> +
![image](https://github.com/Innocent259/Vet-clinic/assets/93039359/b6a10c28-1be5-4b90-b134-5ab04fba91a8)
- [ ] It would be nice if this query return the visit which Maisy Smith has done the first time because Maisy Smith might not be a specialist but she had many visits 🤔 Kindly return her first visit 👍

| Expected Outcome 🟢 |
|-|
| ![image](https://github.com/Innocent259/Vet-clinic/assets/93039359/bb3d4115-17cf-4d0e-b4da-a82885b9ccba) |

2023-08-18 19:17 UTC, HAMMAS-SALEEM commented on queries.sql
>      1;
- [ ] It would be great if you double-check your query because it is returning nothing but as you know that Maisy Smith has done many visits so you are supposed to tell us which specie has been visited the most by Maisy Smith 👍

| Expected Outcome 🟢 |
|-|
| ![image](https://github.com/Innocent259/Vet-clinic/assets/93039359/ca9fa6ca-fe1f-4342-9245-4ccf0e7bc26f) |

2023-08-18 19:17 UTC, HAMMAS-SALEEM commented on data.sql
>  WHERE
**[OPTIONAL BUT HIGHLY RECOMMENDED]**

- [ ] It would be nice if you make your own logo of your name and put that in the readme file at the top to present yourself as a brand in the job market or tech industry to catch the recruiters' eyes 👍

2023-08-18 19:21 UTC, HAMMAS-SALEEM commented on data.sql
> +    ),
![image](https://github.com/Innocent259/Vet-clinic/assets/93039359/a6175bcf-e9c2-4bc5-b489-4580de4003c0)

- [ ] It would be nice if you fix the highlighted link in the image above to make your readme descriptive and professional because right now this link is broken 😨 Kindly fix it or remove it if you don't have any dedicated section for this link 🤔

2023-08-19 06:55 UTC, AbayomiOlaoye requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @Innocent259 :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so_close](https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)


 ## Highlights
- Good PR message ✅ 
- Great commit messages ✅ 
- No linter error ✅ 
- Good attitude to feedback :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 06:55 UTC, AbayomiOlaoye commented on queries.sql
> +ON most_visited_animal.animal_id IN (SELECT animal_id FROM specializations);
- [ ] Sorry to bother you, @Innocent259 :pray: but could you check again because it looks like the change requested by the previous reviewer [here](https://github.com/Innocent259/Vet-clinic/pull/4#discussion_r1298776864) regarding the expected outcome of `Maisy Smith's` specialty when I check your screenshots :point_down: 
![image](https://github.com/Innocent259/Vet-clinic/assets/99715640/c7511ecb-93d4-4d9c-87fa-04260bb72a1b)

I will also suggest that you check again. I am not sure that this was the part meant for that specific `query` - you might want to check line `342`.

2023-08-19 07:06 UTC, Innocent259 commented on queries.sql
> +ON most_visited_animal.animal_id IN (SELECT animal_id FROM specializations);
Hello, @AbayomiOlaoye 
Here is what I found, tell me if it's correct! By the way, I did it before but I forget to remove the previous screenshot which were returning nothing 
![Screenshot from 2023-08-19 08-59-14](https://github.com/Innocent259/Vet-clinic/assets/108480851/55558ad5-e39a-43c4-87b9-ef55c0d724f1)

2023-08-19 09:33 UTC, AbayomiOlaoye approved these changes
## STATUS: APPROVED :green_circle:  

Hi @Innocent259  :wave: :wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Cleanly written code :white_check_mark: 
- App runs well and functions as expected ✅ 
- Great attitude to feedback ✅ 
- Query looks great ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 10:09 UTC, merged